apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  labels:
    instance: etcd-test
    name: etcd
  name: etcd-test-0
  namespace: default
spec:
  holderIdentity: 14a4cf5c19ba5ddd:Leader
  renewTime: ""

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    instance: etcd-test
    name: etcd
  name: druid.gardener.cloud:etcd:etcd-test
  namespace: default
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    instance: etcd-test
    name: etcd
  name: druid.gardener.cloud:etcd:etcd-test
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: druid.gardener.cloud:etcd:etcd-test
subjects:
  - kind: ServiceAccount
    name: etcd-test
    namespace: default
