apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  labels:
    instance: etcd-test
    name: etcd
  name: etcd-test-0
  namespace: default
spec:
  holderIdentity: 14a4cf5c19ba5ddd:Leader
  renewTime: ""