apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    instance: etcd-test
    name: etcd
  name: druid.gardener.cloud:etcd:etcd-test
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: druid.gardener.cloud:etcd:etcd-test
subjects:
  - kind: ServiceAccount
    name: etcd-test
    namespace: default