apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    instance: etcd-test
    name: etcd
  name: druid.gardener.cloud:etcd:etcd-test
  namespace: default
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch