version = 1
SPDX-PackageName = "Gardener etcd-wrapper"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/etcd-wrapper"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2025 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2025 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "vendor/github.com/xiang90/probing/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/xiang90/probing contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/cespare/xxhash/v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/cespare/xxhash/v2 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/sirupsen/logrus/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/sirupsen/logrus contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/go.uber.org/atomic/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.uber.org/atomic contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/google/go-cmp/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/go-cmp contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/beorn7/perks/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/beorn7/perks contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/modern-go/reflect2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/modern-go/reflect2 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/coreos/go-systemd/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/coreos/go-systemd contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/time/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/time contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/prometheus/client_golang/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/client_golang contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/google/uuid/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/uuid contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/google.golang.org/grpc/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 google.golang.org/grpc contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/prometheus/client_model/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/client_model contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/grpc-ecosystem/grpc-gateway/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/grpc-ecosystem/grpc-gateway contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/golang.org/x/crypto/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/crypto contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/golang.org/x/net/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/net contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/go.uber.org/zap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.uber.org/zap contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/coreos/go-semver/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/coreos/go-semver contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/go.etcd.io/bbolt/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.etcd.io/bbolt contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/prometheus/common/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/common contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/go.etcd.io/etcd/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.etcd.io/etcd contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/json-iterator/go/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/json-iterator/go contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/tmc/grpc-websocket-proxy/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/tmc/grpc-websocket-proxy contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/google.golang.org/genproto/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 google.golang.org/genproto contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/gopkg.in/yaml.v2/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/yaml.v2 contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/coreos/pkg/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/coreos/pkg contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/onsi/gomega/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/onsi/gomega contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/gopkg.in/yaml.v3/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 gopkg.in/yaml.v3 contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/google.golang.org/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 google.golang.org/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/dustin/go-humanize/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/dustin/go-humanize contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/soheilhy/cmux/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/soheilhy/cmux contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/grpc-ecosystem/go-grpc-middleware/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/grpc-ecosystem/go-grpc-middleware contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/text/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/text contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/golang-jwt/jwt/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang-jwt/jwt contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/matttproud/golang_protobuf_extensions/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/matttproud/golang_protobuf_extensions contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/gorilla/websocket/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/gorilla/websocket contributors."
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = "vendor/github.com/benbjohnson/clock/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/benbjohnson/clock contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/golang/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/golang/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/grpc-ecosystem/go-grpc-prometheus/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/grpc-ecosystem/go-grpc-prometheus contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/gogo/protobuf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/gogo/protobuf contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/github.com/spf13/pflag/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/spf13/pflag contributors."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "vendor/go.uber.org/multierr/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 go.uber.org/multierr contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/github.com/prometheus/procfs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/prometheus/procfs contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/google/btree/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/google/btree contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/modern-go/concurrent/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/modern-go/concurrent contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/github.com/jonboulle/clockwork/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 github.com/jonboulle/clockwork contributors."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/golang.org/x/sys/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 golang.org/x/sys contributors."
SPDX-License-Identifier = "BSD-3-Clause"
