apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: single-node-etcd
build:
  local: {}
  artifacts:
    - image: etcd-wrapper-image
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - example/common/backuprestore-role-rolebinding.yaml
    - example/common/etcd-client-svc.yaml
    - example/common/etcd-sa.yaml
    - example/singlenode/etcd-cm.yaml
    - example/singlenode/leases.yaml
    - example/singlenode/etcd-sts.yaml

---

apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: multi-node-etcd
build:
  local: {}
  artifacts:
    - image: etcd-wrapper-image
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - example/common/backuprestore-role-rolebinding.yaml
    - example/common/etcd-client-svc.yaml
    - example/common/etcd-sa.yaml
    - example/multinode/leases.yaml
    - example/multinode/etcd-cm.yaml
    - example/multinode/etcd-peer-svc.yaml
    - example/multinode/etcd-peer-netpol.yaml
    - example/multinode/etcd-sts.yaml
