#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "$(dirname "${0}")"/common.sh

#################################################################

echo "> Check..."
make check
echo "All checks are passing"