apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    instance: ${etcd_name}
    name: etcd
  name: druid.gardener.cloud:etcd:${etcd_name}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    instance: ${etcd_name}
    name: etcd
  name: druid.gardener.cloud:etcd:${etcd_name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: druid.gardener.cloud:etcd:${etcd_name}
subjects:
  - kind: ServiceAccount
    name: ${etcd_name}
