apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd-statefulset
    instance: ${etcd_name}
    name: etcd
    role: test
  name: ${etcd_name}-peer
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: peer
      port: 2380
      protocol: TCP
      targetPort: 2380
  publishNotReadyAddresses: true
  selector:
    instance: ${etcd_name}
    name: etcd
  sessionAffinity: None
  type: ClusterIP
